"""
TorusGuard Report Formatter (v0.5.0)
Renders normalized findings and audit reports into Human-First Markdown and JSON.
"""

from typing import Dict, Any, List
from .models import AuditReport, Finding, SeverityLevel, ConfidenceLevel, FindingStatus


class ReportFormatter:
    """
    Produces deterministic, human-readable Markdown and structured JSON audit reports.
    """

    SEVERITY_BADGES = {
        SeverityLevel.CRITICAL: "🔴 Critical",
        SeverityLevel.HIGH: "🟠 High",
        SeverityLevel.MEDIUM: "🟡 Medium",
        SeverityLevel.LOW: "🔵 Low",
        SeverityLevel.INFORMATIONAL: "ℹ️ Info",
    }

    CONFIDENCE_BADGES = {
        ConfidenceLevel.CONFIRMED: "🔒 Confirmed",
        ConfidenceLevel.LIKELY: "⚠️ Likely",
        ConfidenceLevel.NEEDS_REVIEW: "🔍 Needs Review",
        ConfidenceLevel.INFORMATIONAL: "ℹ️ Informational",
        ConfidenceLevel.NOT_APPLICABLE: "⚪ N/A",
    }

    @staticmethod
    def render_markdown(report: AuditReport) -> str:
        report.calculate_summary()
        summary = report.summary_counts

        # Determine overall posture
        if summary.get("critical", 0) > 0 or summary.get("high", 0) > 0:
            posture_icon = "🔴 Action Required"
        elif summary.get("medium", 0) > 0:
            posture_icon = "🟡 Warnings Found"
        else:
            posture_icon = "🟢 Ready / Hardened"

        lines = [
            f"# TorusGuard Security Audit Report",
            f"",
            f"> **Generated by:** TorusGuard `{report.torusguard_version}` (Architecture & Workflow Release)  ",
            f"> **Timestamp:** `{report.generated_at}`  ",
            f"> **Overall Posture:** **{posture_icon}**",
            f"",
            f"---",
            f"",
            f"## 🔍 Detected Stack",
            f"- **Project Name:** `{report.project_name}`",
            f"- **Primary Language:** `{report.detected_stack.get('language', 'Unknown')}`",
            f"- **Framework:** `{report.detected_stack.get('framework', 'Unknown')}`",
            f"- **Data Layer:** `{report.detected_stack.get('data_layer', 'None')}`",
            f"- **Dependency Manager:** `{report.detected_stack.get('dependency_files', 'None')}`",
            f"- **Detection Evidence:** `{report.detected_stack.get('detection_evidence', 'N/A')}`",
            f"- **Detection Confidence:** `{report.detected_stack.get('confidence', 'Confirmed')}`",
            f"",
            f"---",
            f"",
            f"## 📊 Executive Summary",
            f"",
            f"| Metric | Count | Description |",
            f"|---|:---:|---|",
            f"| **Total Findings** | `{summary.get('total', 0)}` | Total normalized security findings detected |",
            f"| **Critical / High** | `{summary.get('critical', 0) + summary.get('high', 0)}` | Urgent vulnerabilities requiring immediate remediation |",
            f"| **Confirmed** | `{summary.get('confirmed', 0)}` | Directly observed with conclusive source/runtime evidence |",
            f"| **Needs Review** | `{summary.get('needs_review', 0)}` | Requires human architectural or business-intent verification |",
            f"| **Remediated** | `{summary.get('remediated', 0)}` | Successfully verified safe post-fix |",
            f"",
            f"---",
            f"",
            f"## 🛡️ Detailed Findings (Lifecycle Stage: Normalized)",
            f"",
        ]

        if not report.findings:
            lines.append("🎉 **No vulnerabilities detected!** Application complies with all TorusGuard security baselines.\n")
        else:
            for idx, f in enumerate(report.findings, 1):
                sev_badge = ReportFormatter.SEVERITY_BADGES.get(f.severity, str(f.severity))
                conf_badge = ReportFormatter.CONFIDENCE_BADGES.get(f.confidence, str(f.confidence))
                loc_str = f"{f.affected_area.target_path}"
                if f.affected_area.start_line:
                    loc_str += f":{f.affected_area.start_line}"
                if f.affected_area.symbol:
                    loc_str += f" (`{f.affected_area.symbol}`)"

                lines.extend([
                    f"### {idx}. [{f.rule_id}] {f.title}",
                    f"",
                    f"- **Severity:** {sev_badge} | **Confidence:** {conf_badge} | **Status:** `{f.status.value}`",
                    f"- **Category:** `{f.category.value}`",
                    f"- **Location:** `{loc_str}`",
                    f"- **Lifecycle Stage:** `{f.lifecycle_stage.value}`",
                ])

                if f.asvs_control or f.cwe:
                    standards = []
                    if f.asvs_control:
                        standards.append(f"OWASP ASVS: `{f.asvs_control}`")
                    if f.cwe:
                        standards.append(f"CWE: `{f.cwe}`")
                    if f.nist_ssdf:
                        standards.append(f"NIST SSDF: `{f.nist_ssdf}`")
                    lines.append(f"- **Standards Mapping:** {', '.join(standards)}")

                lines.extend([
                    f"",
                    f"#### ⚠️ Risk & Rationale",
                    f"{f.rationale}",
                    f"",
                    f"#### 🔎 Evidence",
                ])

                for ev in f.evidence:
                    lines.extend([
                        f"- **Type:** `{ev.type.value}` | **Location:** `{ev.location}`",
                        f"- **Rationale:** {ev.rationale}",
                        f"```",
                        f"{ev.snippet.strip()}",
                        f"```",
                    ])

                lines.extend([
                    f"",
                    f"#### 🛠️ Recommended Remediation",
                    f"**Problem Statement:** {f.remediation.problem_statement}",
                    f"",
                    f"**Action:** {f.remediation.recommended_fix}",
                    f"",
                    f"**Code Pattern ({f.remediation.framework_pattern.framework}):**",
                    f"```diff",
                    f"- // UNSAFE",
                    f"- {f.remediation.framework_pattern.unsafe_snippet.strip()}",
                    f"+ // SAFE REMEDIATION",
                    f"+ {f.remediation.framework_pattern.safe_snippet.strip()}",
                    f"```",
                    f"",
                    f"**Verification Method:** {f.remediation.verification_method}",
                    f"",
                    f"**Residual Risk Notes:** {f.remediation.residual_risk_notes}",
                    f"",
                    f"---",
                    f"",
                ])

        lines.extend([
            f"## 📋 Verification & Next Steps",
            f"1. **Apply Proposed Remediations:** Execute framework-native code fixes following the snippets above.",
            f"2. **Execute Differential Re-check:** Run `/torusguard recheck` to verify that findings transition to `Verified Safe`.",
            f"3. **Resolve Needs Review Items:** Inspect domain service layers, reverse proxy routing, and cloud IAM permissions.",
            f"",
            f"---",
            f"",
            f"## ⚖️ Technical Boundaries & Integrity",
            f"TorusGuard is a Markdown-first security guidance framework for AI coding agents and human engineers. It is not an automated binary scanner, dynamic vulnerability scanner, or penetration-testing replacement. Findings categorized as `Needs Review` require manual verification of out-of-band architecture.",
        ])

        return "\n".join(lines)
